name: "Zenhub Pipeline Automation"
description: "Automate moving ZenHub cards between pipelines based on Github issue or pull request status."
inputs:
  zenhub-graphql-personal-api-key:
    description: "ZenHub API token."
    required: true
  zenhub-workspace:
    description: "ZenHub workspace name."
    required: true
  # pull-request-state-mapping:
  #   description: "Provide a mapping between Pull Request status and the corresponding ZenHub Pipeline you want to move the issue to. Possible statuses are: open, closed, merged, commented, changes_requested, approved, dismissed."
  #   required: true
  #   default: '{open: "In Progress"}'
outputs:
  zenhub-issue-id:
    description: "The ZenHub ID of the pull request."
  zenhub-pipeline-id:
    description: "The ZenHub Pipeline ID."
  zenhub-pipeline-name:
    description: "The ZenHub Pipeline name."
  zenhub-workspace-id:
    description: "The Zenhub ID of the referenced workspace."
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: star
  color: blue
